### ISSUE TITLE
Cannot find module 'D:\Intership\Geojsontopng\geojson2png\node_modules\mapnik\lib\binding\node-v48-win32-x64\mapnik_settings.js'

### ISSUE THREAD

**Issue by nguyenvantan061195** [chk1/geojson2png#1]
D:\Intership\Geojsontopng\geojson2png>node example2.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\Intership\Geojsontopng\geojson2png\node_modules\mapnik\lib\binding\node-v48-win32-x64\mapnik_settings.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Intership\Geojsontopng\geojson2png\node_modules\mapnik\lib\mapnik.js:8:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Help me Pls !

**Comment by manhlh** [comment]
Delete node_module and try run "npm install" . good luck for you
